services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Kematjaya\URLBundle\Twig\DeleteExtension:
        tags: ['twig.extension']
        
    Kematjaya\URLBundle\Twig\UrlExtension:
        tags: ['twig.extension']
        
    Kematjaya\URLBundle\Storage\CredentialStorageInterface:
        class: Kematjaya\URLBundle\Storage\RoutingCredentialStorage
        
    Kematjaya\URLBundle\Factory\RoutingFactoryInterface:
        class: Kematjaya\URLBundle\Factory\RoutingFactory
        
    Kematjaya\URLBundle\Source\RoutingSourceInterface:
        class: Kematjaya\URLBundle\Source\YamlRoutingSource