services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Kematjaya\URLBundle\Twig\DeleteExtension:
        tags: ['twig.extension']
        
    Kematjaya\URLBundle\Twig\UrlExtension:
        tags: ['twig.extension']
        
    Kematjaya\URLBundle\Storage\CredentialStorageInterface:
        class: Kematjaya\URLBundle\Storage\RoutingCredentialStorage
        
    Kematjaya\URLBundle\Factory\RoutingFactoryInterface:
        class: Kematjaya\URLBundle\Factory\RoutingFactory
        
    Kematjaya\URLBundle\Source\RoutingSourceInterface:
        class: Kematjaya\URLBundle\Source\YamlRoutingSource
        
    Kematjaya\URLBundle\Transformer\AccessControlTransformer:
        class: Kematjaya\URLBundle\Transformer\AccessControlTransformer
        
    Kematjaya\URLBundle\Console\RoutingCommand:
        class: Kematjaya\URLBundle\Console\RoutingCommand
        tags:
            -  { name: console.command }
            
    Kematjaya\URLBundle\Repository\URLRepositoryInterface:
        class: Kematjaya\URLBundle\Repository\URLRepository
        
    Kematjaya\URLBundle\Type\AccessControlType: ~
    Kematjaya\URLBundle\Type\ControlType: ~